sudo: false
dist: trusty

language: python
matrix:
  include:
    - python: '2.7'
    - python: '3.5'
    - python: '3.6'
    - python: pypy2.7-5.8.0
      env: NO_COVERAGE=1
    - python: pypy3.5-5.8.0
      env: NO_COVERAGE=1
    # Docker dev image
    - sudo: required
      services: docker
      env:
        - IMAGE_NAME=praekeltfoundation/marathon-acme
        - REGISTRY_USER=praekeltorgdeploy
        - secure: "JSuiWKoxXNr77SYOuYC1RBXl4vXthOBmMxdKJ5ZjPNCkcAC1WeiFlEAYSA1rw+iuNIi0SWhU8ATTOVj+iKWH3aYx3RolCngMf18juFKGktUdQ17EimK2KzGeieyaBIuwRg+sYelgydC4J+d7pqDGAwhaqvU+xTJeKQUhavUIiymNrAZee008f/ncrporBHPTFHQIWbexYdd2ta/zO9Y3VOQqxJP5qp9E6uRAvvl9ZkNIFGcuRYylPbFIiR5QF6guEXks8bnhlnfflxSJUoX9z6NYeG/kQXyk84p4a2fRm7wuFn4XSbjY+G0Rik4tPq1+rBI7QdKM1YOctiej/Mmb0WD8sEkBGlQDwBb5oozdPY3MtqmtFcSXgf7o0yJWaoLt+l1LBKY1NQg+n59Ls7jnxX+pmR5d42W9lDLHPVVadyun+n4aMUhkbTYxlr1y4vAaAoogB6V9K4QRKekJ4i9mnTiVg29XLuqkZpKQjH6BNMMpy1kPML9tGx9cV+5dUGn2qC097YqmepvUCEIcRs0GJt1I7fNgb0VvyFQu3S/gFqVKVL8qZLWJFCs+TrII6x6ePp+iq5SQvST5YvWQ7JvZY9bnUnqsCBpa0Q1te2jyRk4AVJvd8oPBmt4z2OiJFahWnUvAbXduTW9fH9KhwbSw1nxi1lTSbpw/l+PLbocORKc="

      # Clear unused steps
      addons: {}
      before_install: []
      install: []
      after_success: []

      before_script:
        - docker pull $IMAGE_NAME:develop || true
      script:
        - docker build --pull --cache-from $IMAGE_NAME:develop -t $IMAGE_NAME .

      before_deploy:
        - pip install docker-ci-deploy==0.3.0
        - docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
      deploy:
        provider: script
        script: dcd -t develop -V "$(git rev-parse --short HEAD)" -L praekeltfoundation/marathon-acme
        on:
          branch: develop

cache: pip
addons:
  apt_packages:
    - pandoc

before_install:
  - pip install --upgrade pip
install:
  - pip install -r requirements-dev.txt
  - if [[ -z "$NO_COVERAGE" ]]; then pip install codecov; fi

script:
  - if [[ -z "$NO_COVERAGE" ]]; then COVERAGE_OPT="--cov"; else COVERAGE_OPT=""; fi
  - py.test marathon_acme $COVERAGE_OPT
  - flake8 .

after_success:
  - if [[ -z "$NO_COVERAGE" ]]; then codecov; fi

before_deploy:
  - pandoc --from=markdown --to=rst --output=README.rst README.md
deploy:
  provider: pypi
  user: praekelt.org
  password:
    secure: YeufUcQa0CkVMJ+1KMAYvfKmAeODrxxxnoFx0Id9jpUeCc6OmLNzX60KgMf/1nW7VLksB+qwx/nXmXCfuwJ2y5C2Cgqn0LhM3aBXagvoqePTqrnGLuoE1YkYrNb6Q5l/QKJrVzYgINzNT2lHTwzM9cA0d3eEsUm58wtt7zRrkmgRGdLz4eL2ApgKI9rtc3fx2iiwOjPwHnuclIvv4IWE+IxzUZQ5PMlZzpV3X2mqkGir0+WL4ySo+lgY+Em96A2vWkfyfBSTxAKI+If9KhqcIZVVsYSoMktPiqM4XYqloZ62TaZgvgdd/gQ+Kcn0WMBO7pfGnV3TixJ8nId7uURDbM1p6qt1SRN0VNzXn38TK1TQuj0D4cUS/xrIO+Y6qP6akiG6RVA0ty4Rx/pi/5TIWOk3G4Mgfli/6X2ndE3jFVMK+JwEtfxHZAZYaHJ0c1wZoaFUtaKjVdvH7sOlyuuPsXYH5KUoN5j9zzxR8p+YB8iqGl4KMmW0F4PcLPKv8EoHjU4GjR6I0dfGB4BhE/m2YW9TclDbDCtr9nHVcOEImgefjuAdw70pYeYrVpKVO7MBKqbl2HjqoHhkU5QneShwuEP+kVLVAWJGwd73TRobvMgXwu4upzLEer5RweuhtV8526zXJKZGUp3pz0YDEc9VwfvuxT42ayGODi8JfP9s46Q=
  distributions: sdist bdist_wheel
  on:
    tags: true
